# Generated by Django 3.2.16 on 2024-09-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_name_group_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='default-group', unique=True),
        ),
    ]
